spring:
  profiles:
    include: oauth, db
  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8InnoDBDialect
  # session
  session:
    store-type: jdbc
  mvc:
    hiddenmethod:
      filter:
        enabled: true