spring:
  profiles:
    include: real1, oauth, db
  config:
    use-legacy-processing: true
  # JPA
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect
    open-in-view: false
  # session
  session:
    store-type: jdbc
  mvc:
    hiddenmethod:
      filter:
        enabled: true